config/routes.rb
Weddingz::Application.routes.draw do

  root :to => redirect("/users/sign_in")

  resources :service_types

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :services
  get '/weddings/activated'
  
  resources :weddings do
    get 'activate', :on => :member    
    resources :services do 
      get 'activate', :on => :member
      get 'disable' , :on => :member
    end
  end

  match '/weddings/:id/activate_services/:service_ids' => 'weddings#activate_services'
  match '/weddings/:id/disable_services/:service_ids'  => 'weddings#disable_services'
  
  devise_for :users#, :controllers => { :registrations => "users" }

end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :service_type
  has_many   :services_weddings
  has_many   :weddings, :through => :services_weddings
  
  def pictures_url_array
    self.pictures_url.split(';')
  end
  
  def as_json(options)
    {
      id:            self.id,
      name:          self.name || '',
      phone_number:  self.phone_number || '',
      address:       self.address || '',
      summary:       self.summary || '',
      type:          self.service_type.name || '',
      description:   self.description || '',
      price:         self.price || '',
      front_picture: self.front_picture || '',
      pictures_url:  self.pictures_url.split(';') || '',
      price_form:    self.price_form || 0
    }
  end
end

app/models/service_type.rb
class ServiceType < ActiveRecord::Base
  has_many :services

  has_many :service_types_weddings
  has_many :weddings, :through => :service_types_weddings

  def as_json(option) 
      {
      id:        self.id,
      name:      self.name,
      image_url: self.image_url || '',
      icon_url:  self.icon_url || ''
    }
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_filter :wedding

  # GET /services
  # GET /services.json
  def wedding
    if(params[:wedding_id])
      @wedding = Wedding.find(params[:wedding_id])
    else
      @wedding = Wedding.first # Service.all <= What the fuck was that?
    end
  end
  
  def index
    if(params[:wedding_id])
      if params[:service_type_id]
        @activated_services = ServicesWedding.activated_services(params[:wedding_id], params[:service_type_id]) || []
        @disabled_services  = ServicesWedding.disabled_services(params[:wedding_id], params[:service_type_id]) || []
      else
        @services = Wedding.find(params[:wedding_id]).services
      end
    else
      @services = Service.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: { activated_services: @activated_services, disabled_services: @disabled_services }}
    end
  end


  def activate
    service_wedding = ServicesWedding.where(:wedding_id => params[:wedding_id], :service_id => params[:id]).first
    service_wedding.activated = true
    service_wedding.save
    respond_to do |format|
      format.html {render :text => "success"}
      format.json {render :json => {status: "success"}}
    end
  end

  def disable
    service_wedding = ServicesWedding.where(:wedding_id => params[:wedding_id], :service_id => params[:id]).first
    service_wedding.activated = false
    service_wedding.save
    respond_to do |format|
      format.html {render :text => "success"}
      format.json {render :json => {status: "success"}}
    end
  end

  ######################## DEFAULT ########################
  # GET /services/1
  # GET /services/1.json
  def show
    @service = Service.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @service }
    end
  end

  # GET /services/new
  # GET /services/new.json
  def new
    @service = Service.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @service }
    end
  end

  # GET /services/1/edit
  def edit
    @service = Service.find(params[:id])
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(params[:service])
    @service.weddings << @wedding
    respond_to do |format|
      if @service.save
        format.html { redirect_to [@wedding, @service], notice: 'Service was successfully created.' }
        format.json { render json: @service, status: :created, location: @service }
      else
        format.html { render action: "new" }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /services/1
  # PUT /services/1.json
  def update
    @service = Service.find(params[:id])

    respond_to do |format|
      if @service.update_attributes(params[:service])
        format.html { redirect_to [@wedding, @service], notice: 'Service was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service = Service.find(params[:id])
    @service.destroy

    respond_to do |format|
      format.html { redirect_to services_url }
      format.json { head :ok }
    end
  end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_for([@wedding, @service]) do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :phone_number %><br />
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing service</h1>

<%= render 'form' %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', wedding_services_path %>

app/views/services/index.html.erb
<ul class="activated_services">
  <% @activated_services.each do |service| %>
    <li data-id="<%= service.id %>">
      <div class="togglable">
        <div class="top">
          <button data-action="activate" data-value ="false">x</button>
          <h3 class="click_toggler"><%= service.name %></h3>
          <%= image_tag service.front_picture, :class => 'front_picture' %>
        </div>  
        <div class="toggler_content">
          <div class="price"><%= service.price %></div>
          <div class='galery'>
            <% service.pictures_url_array.each do |picture_url| %>
              <%= image_tag picture_url %>
            <% end %>
          </div>
          <div class="more">
            <div class="address"><%= service.address %></div>
            <div class="description"><%= service.description %></div>
          </div>
        </div>
      </div>
    </li>
  <% end %>
</ul>


<ul class="disabled_services">
  <% @disabled_services.each do |service| %>
    <li data-id="<%= service.id %>">
      <div class="togglable">
        <div class="top">
          <button data-action="activate" data-value ="true">Réactiver</button>
          <h3 class="click_toggler"><%= service.name %></h3>
          <%= image_tag service.front_picture, :class => 'front_picture' %>
        </div>
        <div class="toggler_content">
          <div class="price"><%= service.price %></div>
          <div class='galery'>
            <% service.pictures_url_array.each do |picture_url| %>
              <%= image_tag picture_url %>
            <% end %>
          </div>
          <div class="more">
            <div class="address"><%= service.address %></div>
            <div class="description"><%= service.description %></div>
          </div>
        </div>
      </div>
    </li>
  <% end %>
</ul>

app/views/services/new.html.erb
<h1>New service</h1>

<%= render 'form' %>

<%= link_to 'Back', wedding_services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Phone number:</b>
  <%= @service.phone_number %>
</p>

<p>
  <b>Address:</b>
  <%= @service.address %>
</p>

<p>
  <b>Image url:</b>
  <%= @service.image_url %>
</p>

<p>
  <b>Name:</b>
  <%= @service.name %>
</p>


<%= link_to 'Edit', edit_wedding_service_path(@service) %> |
<%= link_to 'Back', wedding_services_path %>