config/routes.rb
Weddingz::Application.routes.draw do

  root :to => redirect("/users/sign_in")

  resources :service_types

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :services
  get '/weddings/activated'
  
  resources :weddings do
    get 'activate', :on => :member    
    resources :services do 
      get 'activate', :on => :member
      get 'disable' , :on => :member
    end
  end

  match '/weddings/:id/activate_services/:service_ids' => 'weddings#activate_services'
  match '/weddings/:id/disable_services/:service_ids'  => 'weddings#disable_services'
  
  devise_for :users#, :controllers => { :registrations => "users" }

end

app/controllers/service_types_controller.rb
class ServiceTypesController < InheritedResources::Base
  def index
    @service_types = ServiceType.all
    respond_to do |format|
      format.json { render :json => @service_types }
    end
  end
end

app/helpers/service_types_helper.rb
module ServiceTypesHelper
end

app/views/service_types/_form.html.erb
<%= form_for(@service_type) do |f| %>
  <% if @service_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service_type.errors.count, "error") %> prohibited this service_type from being saved:</h2>

      <ul>
      <% @service_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label : %><br />
    <%= f.text_field : %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/service_types/edit.html.erb
<h1>Editing service_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @service_type %> |
<%= link_to 'Back', service_types_path %>

app/views/service_types/index.html.erb
<h1>Listing service_types</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @service_types.each do |service_type| %>
  <tr>
    <td><%= service_type. %></td>
    <td><%= link_to 'Show', service_type %></td>
    <td><%= link_to 'Edit', edit_service_type_path(service_type) %></td>
    <td><%= link_to 'Destroy', service_type, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Service type', new_service_type_path %>

app/views/service_types/new.html.erb
<h1>New service_type</h1>

<%= render 'form' %>

<%= link_to 'Back', service_types_path %>

app/views/service_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>:</b>
  <%= @service_type. %>
</p>


<%= link_to 'Edit', edit_service_type_path(@service_type) %> |
<%= link_to 'Back', service_types_path %>