config/routes.rb
Weddingz::Application.routes.draw do

  root :to => redirect("/users/sign_in")

  resources :service_types

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :services
  get '/weddings/activated'
  
  resources :weddings do
    get 'activate', :on => :member    
    resources :services do 
      get 'activate', :on => :member
      get 'disable' , :on => :member
    end
  end

  match '/weddings/:id/activate_services/:service_ids' => 'weddings#activate_services'
  match '/weddings/:id/disable_services/:service_ids'  => 'weddings#disable_services'
  
  devise_for :users#, :controllers => { :registrations => "users" }

end

app/models/wedding.rb
# encoding: utf-8
class Wedding < ActiveRecord::Base
  has_many :services_weddings
  has_many :services, :through => :services_weddings
  
  has_many :clients, :class_name => "Users::Client"
  has_one :organizer, :class_name => "Users::Organizer"  
  
  has_many :service_types_weddings
  has_many :service_types, :through => :service_types_weddings

  before_create :add_services
  before_create :create_client_account
    
  def services_by service_type
    if service_type.kind_of? Integer
      self.services.reject{|service| service.id != service_type}
    else
      self.services.reject{|service| service.service_type.name.downcase != service_type.downcase}
    end
  end
  
  def activated_services_types
    self.service_types_weddings.reject{|service_types_wedding| !service_types_wedding.activated?}
  end

  def disabled_services_types
    self.service_types_weddings.reject{|service_types_wedding| service_types_wedding.activated?}
  end
  
  def activated_services(service_type_id=nil)
     _service_weddings = self.services_weddings.reject{ |service_wedding| !service_wedding.activated? } # Reject all disabled services
     retrieve_service_types(_service_weddings, service_type_id)
  end

  def disabled_services(service_type_id=nil)
     _service_weddings = self.services_weddings.reject{ |service_wedding| service_wedding.activated? } # Reject all disabled services
     retrieve_service_types(_service_weddings, service_type_id)
  end  
  
  def as_json(options)
    {
      id:                 self.id,
      budget:             self.budget     || 0,
      place:              self.place      || '',
      nb_person:          self.nb_person  || 0,
      has_child:          self.has_child  || false,
      period:             self.period  || '',

      bride_first_name:   self.bride_first_name,
      bride_last_name:    self.bride_last_name,
      bride_phone_number: self.bride_phone_number || '',
      bride_email:        self.bride_email        || '',
                       
      groom_first_name:   self.groom_first_name,
      groom_last_name:    self.groom_last_name,
      groom_phone_number: self.groom_phone_number || '',
      groom_email:        self.groom_email        || '',
            
      religion:           self.religion           || '',
      place_type:         self.place_type         || '',
      desired_atmosphere: self.desired_atmosphere || '',
      
      note:               self.note          || '',
      bride_photo:        self.bride_photo   || '',
      groom_photo:        self.groom_photo   || '',
      wedding_photo:      self.wedding_photo || '',
      
      service_types:      self.service_types_weddings,
      
      last_update:        self.updated_at
    } 
    
  end
  
  private
  def retrieve_service_types(_service_weddings, _service_type_id)
    if _service_type_id.nil?
      _service_weddings = _service_weddings.collect{ |service_wedding| service_wedding.service } # Collect all the service
    else
      # Reject services with bad service type id
      _service_weddings = _service_weddings.reject{ |service_wedding| service_wedding.service_type.id != _service_type_id.to_i } 
      _service_weddings = _service_weddings.collect{ |service_wedding| service_wedding.service} # Collect all the service
    end
    _service_weddings  
  end
  
  def add_services
    self.services << Service.all
  end

  def create_client_account
    if self.groom_email
      bride = Users::Client.create(username: self.bride_email, password: 'password')
      self.clients << bride
    end
    if self.groom_email
      groom = Users::Client.create(username: self.groom_email, password: 'password')
      self.clients << groom
    end
  end
end

app/controllers/weddings_controller.rb
# encoding: utf-8
class WeddingsController < ApplicationController
  before_filter :authenticate_user!, :except => [:activate, :activated, :show, :index, :create, :update, :activate_services, :disable_services]
  
  def activate
    weddings = Wedding.all
    weddings.each do |wedding|
      wedding.activated = false
      wedding.save
    end
    wedding = Wedding.find(params[:id])
    wedding.activated = true
    wedding.save
    respond_to do |format|
      format.json { render json: wedding}
    end

  end
  
  def activated
    wedding = Wedding.where(:activated => true).first
    if wedding.nil?
      respond_to do |format|
        format.json { render :text => "Aucun wedding n'est activé"}
      end
    else
      respond_to do |format|
        format.json { render :json => wedding }
      end
    end
  end
  
  def activate_services
    params[:service_ids].split(';').each do |service_id|
      w = ServicesWedding.where(:wedding_id => params[:id], :service_id => service_id).first
      w.activated = true
      w.save
    end
    respond_to do |format|
      format.html {render :text => "success"}
      format.json {render :json => {status: "success"}}
    end
  end
  def disable_services
    params[:service_ids].split(';').each do |service_id|
      w = ServicesWedding.where(:wedding_id => params[:id], :service_id => service_id).first
      w.activated = false
      w.save
    end
    respond_to do |format|
      format.html {render :text => "success"}
      format.json {render :json => {status: "success"}}
    end
  end
  
  # GET /weddings
  # GET /weddings.json
  def index
    @weddings = Wedding.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @weddings }
    end
  end

  # GET /weddings/1
  # GET /weddings/1.json
  def show
    @wedding = Wedding.find(params[:id])

    @service_type_id = params[:service_type_id] || ServiceType.where(:name => "Fleuristes").first.id
    
    @activated_services = @wedding.activated_services(@service_type_id)
    @disabled_services = @wedding.disabled_services(@service_type_id)

    @services_types_wedding =  @wedding.service_types_weddings.find_all{|c| c.activated? } # Only activated services types

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @wedding }
    end
  end

  # GET /weddings/new
  # GET /weddings/new.json
  def new
    @wedding = Wedding.new
    @services = Service.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @wedding }
    end
  end

  # GET /weddings/1/edit
  def edit
    @wedding = Wedding.find(params[:id])
  end

  # POST /weddings
  # POST /weddings.json
  def create
    @wedding = Wedding.new(params[:wedding])
    if (!params[:wedding][:service_type_ids])
      params[:wedding][:service_type_ids] = params[:wedding][:service_type_ids].split(';')
    end
    params[:wedding][:service_type_ids] ||= []
    ServiceType.all.each do |service_type|
      @wedding.service_types_weddings << ServiceTypesWedding.create(:service_type_id => service_type.id, 
                                                                    :wedding_id      => @wedding.id,
                                                                    :activated    => params[:wedding][:service_type_ids].include?(service_type.id.to_s))
    end

    respond_to do |format|
      if @wedding.save
        format.html { redirect_to @wedding, notice: 'Wedding was successfully created.' }
        format.json { render json: @wedding, status: :created, location: @wedding }
      else
        format.html { render action: "new" }
        format.json { render json: @wedding.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /weddings/1
  # PUT /weddings/1.json
  def update
    @wedding = Wedding.find(params[:id])

    respond_to do |format|
      if @wedding.update_attributes(params[:wedding])
        format.html { redirect_to @wedding, notice: 'Wedding was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @wedding.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weddings/1
  # DELETE /weddings/1.json
  def destroy
    @wedding = Wedding.find(params[:id])
    @wedding.destroy

    respond_to do |format|
      format.html { redirect_to weddings_url }
      format.json { head :ok }
    end
  end
end

app/helpers/weddings_helper.rb
module WeddingsHelper
end

app/views/weddings/_form.html.haml
= form_for(@wedding) do |f|
  - if @wedding.errors.any? 
    #error_explanation
    %h2= pluralize(@wedding.errors.count, "error")  prohibited this wedding from being saved:
    %ul
      - @wedding.errors.full_messages.each do |msg| 
      %li = msg 

  .field
    = f.label :budget 
    %br/
    = f.text_field :budget 
  .field
    = f.label :place 
    %br/
    = f.text_field :place 
  .field
    = f.label :nb_person 
    %br/
    = f.text_field :nb_person 
  .field
    = f.label :nb_child 
    %br/
    = f.text_field :nb_child 
  .field
    = f.label :organizer_id 
    %br/
    = f.text_field :organizer_id 
  .field
    = f.label :client_id 
    %br/
    = f.text_field :client_id 
  .actions
    = f.submit 

app/views/weddings/edit.html.erb
<h1>Editing wedding</h1>

<%= render 'form' %>

<%= link_to 'Show', @wedding %> |
<%= link_to 'Back', weddings_path %>

app/views/weddings/new.html.erb
<h1>New wedding</h1>

<%= render 'form' %>

<%= link_to 'Back', weddings_path %>

app/views/weddings/show.html.erb
<% content_for :css do %>
  <%= stylesheet_link_tag 'services' %>
  <%= stylesheet_link_tag 'weddings' %>
<% end %>

<script type="text/javascript">
  wedding_id = <%= @wedding.id %>
</script>
<h1><%= "#{@wedding.bride_first_name} et #{@wedding.groom_first_name}" %></h1>
<div id="wrapper">
  <% if is_mobile? %>
    <div id="select_div"><%= select("service", "service_type", @services_types_wedding.collect{|c| [c.service_type.name, c.service_type.id ]}) %></div>
  <% else %>
    <div id="left">
      <div>
      <ul class="services">
        <% @services_types_wedding.each do |service_type_wedding| %>
            <li class="<%= service_type_wedding.service_type.id == @service_type_id ? 'selected' : '' %>" data-service-type-id="<%= service_type_wedding.service_type.id %>">
              <div class="img"><%= image_tag service_type_wedding.service_type.icon_url %></div>
              <div class="text"><%= service_type_wedding.service_type.name %></div>
            </li>
        <% end %>
      </ul>
      </div>
    </div>
  <% end %>
  <div id="content">
    <h2>Services pré-sélectionnés</h2>
    <ul class="activated_services">
      <% if @activated_services.empty? %>
        <li class="no_data">Aucun service pré-séléctionné</li>
      <% else %>
          <% @activated_services.each do |serv| %>
            <li data-id="<%= serv.id %>">
            <div class="togglable">
              <div class="top">
                <h3><%= serv.name %></h3>
                <button class="no_button" data-action="activate" data-value="false">Mettre de côté</button>
              </div>
              <div class="middle">
                  <img class="front_picture" src="<%= serv.front_picture %>" />
                  <div class="summary"><%= serv.summary %></div>
              </div>          
              <div class="toggler_content">
                <div class="slideshow">
                  <div class="slidesContainer">
                  <% serv.pictures_url.split(';').each do |pic| %>
                    <div class="slide"><img src="<%= pic %>" /></div>
                  <% end %>
                  </div>
                </div>
                <div class="more">
                    <div class="price"><%= serv.price %></div>
                  <div class="address"><%= serv.address %></div>
                  <div class="description"><%= serv.description %></div>
                </div>
              </div>
              <div class="click_toggler more_info"></div>
            </div>
        </li>
          <% end %>
        <% end %>
    </ul>
    <h2>Services mis de côtés</h2>
     <ul class="disabled_services">
      <% if @disabled_services.empty? %>
        <li class="no_data">Aucun service mis de de côté</li>
      <% else %>
          <% @disabled_services.each do |serv| %>
            <li data-id="<%= serv.id %>"><div class="togglable">
              <div class="top">
                <h3><%= serv.name %></h3>
                <button class="no_button" data-action="activate" data-value="true">Activer</button>
              </div>
              <div class="middle">
                  <img class="front_picture" src="<%= serv.front_picture %>" />
                  <div class="summary"><%= serv.summary %></div>
              </div>
              <div class="toggler_content">
                <div class="slideshow">
                  <div class="slidesContainer">
                  <% serv.pictures_url.split(';').each do |pic| %>
                    <div class="slide"><img src="<%= pic %>" /></div>
                  <% end %>
                  </div>
                </div>
                <div class="more">
                    <div class="price"><%= serv.price %></div>
                  <div class="address"><%= serv.address %></div>
                  <div class="description"><%= serv.description %></div>
                </div>
              </div>
              <div class="click_toggler more_info"></div>
            </div>
            </li>
          <% end %>
        <% end %>
    </ul>
  </div>
</div>

<script id="service_template" type="text/x-handlebars-template">
  <li data-id="{{id}}">
  <div class="togglable">
    <div class="top">
      <h3>{{name}}</h3>
      <button class="no_button" data-action="activate" data-value ="false">Mettre de côté</button>
    </div>
    <div class="middle">
        <img class="front_picture" src="{{front_picture}}" />
        <div class="summary">{{summary}}</div>
    </div>
    <div class="toggler_content">
      <div class="slideshow">
        <div class="slidesContainer">
          {{#each pictures_url}}
            <div class="slide"><img src="{{this}}" /></div>
          {{/each}}
        </div>
      </div>
      <div class="more">
          <div class="price">{{price}}</div>
        <div class="address">{{address}}</div>
        <div class="description">{{description}}</div>
      </div>
    </div>
    <div class="click_toggler more_info"></div>
  </div>
  </li>
</script>

<script id="service_template_disable" type="text/x-handlebars-template">
  <li data-id="{{id}}">
  <div class="togglable">
    <div class="top">
      <h3>{{name}}</h3>
      <button class="no_button" data-action="activate" data-value ="true">Activer</button>
    </div>
    <div class="middle">
        <img class="front_picture" src="{{front_picture}}" />
        <div class="summary">{{summary}}</div>
    </div>
    <div class="toggler_content">
      <div class="slideshow">
        <div class="slidesContainer">
          {{#each pictures_url}}
            <div class="slide"><img src="{{this}}" /></div>
          {{/each}}
        </div>
      </div>
      <div class="more">
          <div class="price">{{price}}</div>
        <div class="address">{{address}}</div>
        <div class="description">{{description}}</div>
      </div>
    </div>
    <div class="click_toggler more_info"></div>
  </div>
  </li>
</script>

<script type="text/javascript">
        $('.togglable .click_toggler').click(function () {
            $(this).closest('.togglable').toggleClass('open');
        });
</script>


<script type="text/javascript">
$(document).ready(function(){
   $('.slidesContainer').css('overflow', 'hidden');

  $('.slideshow').each(function() {
      var slideshow = this;
    	//Configuration
		  var retour = true;
		  var tempsTransition = 1000;
	  	var tempsAttente = 6000;
			
		  var currentPosition = 0;
		  var slideWidth = $("#mobile").length != 1 ? 510 : 340 ;
		  var slides = $(slideshow).find('.slide');
		  var numberOfSlides = slides.length;
		  var interval;
      
      // Supprime la scrollbar en JS
    
      // Attribue  #slideInner  à toutes les div .slide
      slides.wrapAll('<div class="slideInner"></div>')
        // Float left to display horizontally, readjust .slides width
    	.css({
          'float' : 'left',
          'width' : slideWidth
        });
    
      // Longueur de #slideInner égale au total de la longueur de tous les slides
      $(slideshow).find('.slideInner').css('width', slideWidth * numberOfSlides);
    
      // Insert controls in the DOM
      $(slideshow).prepend('<span class="control leftControl">Précédent</span>')
                   .append('<span class="control rightControl">Suivant</span>');
    
    
      
      // Hide left arrow control on first load
      manageControls(currentPosition);
    
      //Crée un écouteur d'évènement de type clic sur les classes .control
      $(slideshow).find('.control').bind('click', function(){
        // Determine la nouvelle position
      	currentPosition = ($(this).hasClass('rightControl') ? currentPosition + 1 : currentPosition - 1);
          
      	if(currentPosition == numberOfSlides && retour == false ){
      		currentPosition--;
      		pause();
      	}  	
      	// Cache ou montre les controles
        manageControls(currentPosition);
        // Fais bouger le slide
        $(slideshow).find('.slideInner').animate({
          'marginLeft' : slideWidth*(-currentPosition)
        },tempsTransition);
      });
    
      // manageControls: Cache ou montre les flêches de controle en fonction de la position courante
      function manageControls(position){
        // Cache la fleche "précédent" si on est sur le premier slide
      	if(position==0){ $(slideshow).find('.leftControl').hide() } else{ $(slideshow).find('.leftControl').show() }
      	// Cache la fleche "suivant" si on est sur le dernier slide (et que le retour automatique n'est pas activé)
        if(position==numberOfSlides-1 && retour == false){
    	   	$(slideshow).find('.rightControl').hide();
      	} else {
      		$(slideshow).find('.rightControl').show();
      	}
        if(position == numberOfSlides && retour == true){
          currentPosition = 0;
    	 	  $(slideshow).find('.leftControl').hide();
    	  }
      }
      function suivant(){
      	$(slideshow).find('.rightControl').click();
    	}
  });
  

});
</script>